name: Build

on:
  push:
    branches:
      - master
      - 2.2.x
      - 2.3.x
  pull_request:
    types: [labeled]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || contains( github.event.pull_request.labels.*.name, 'run integration tests') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - run: ./mvnw install
